[pytest]
markers =
    book_test: All book tests
    avail_test: Available books
    borrow_test: Borrow related tests
    return_test: Return related tests
    book_details: Test book details
    borrow_and_return: Test if both borrow and return properly
    library_test: All library tests
    library_details: Test library details
    add_remove: Add and remove functions
    find_book: Find books test
    total_books: Total books test
    fetch_book_info: Fetch book info function
    excep: For all exceptions